#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd -- "$(dirname -- "$0")" && pwd -P)"
cd "$ROOT"
log() { printf '[baize-wechatsync-docker] %s\n' "$*"; }
fail() { log "ERROR: $*" >&2; exit 1; }
[ "$#" -eq 0 ] || fail 'Usage: bash install.sh'
command -v docker >/dev/null 2>&1 || fail 'Docker is required'
docker info >/dev/null 2>&1 || fail 'Docker daemon is unavailable'
docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required'
[ -f image.tar.gz ] || fail 'image.tar.gz not found; use the complete Docker release ZIP'
[ ! -L .env ] || fail '.env cannot be a symlink'
if [ ! -e .env ]; then
  command -v od >/dev/null 2>&1 || fail 'od is required to generate secure tokens'
  command -v tr >/dev/null 2>&1 || fail 'tr is required to generate secure tokens'
  token_bridge="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
  token_http="$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
  [ "$token_bridge" != "$token_http" ] || fail 'Random token collision'
  (
    umask 077
    cat > .env <<ENV
# Generated by Baize Docker installer. Never commit or publish this file.
WECHATSYNC_TOKEN=$token_bridge
WECHATSYNC_HTTP_TOKEN=$token_http
WS_BIND_IP=127.0.0.1
WS_HOST_PORT=9527
MCP_BIND_IP=127.0.0.1
MCP_HOST_PORT=9528
ENV
  )
  log 'Generated two independent random tokens in .env (not printed)'
else
  log 'Reusing existing .env without overwriting credentials'
fi
chmod 600 .env
for key in WECHATSYNC_TOKEN WECHATSYNC_HTTP_TOKEN; do
  grep -Eq "^$key=[a-fA-F0-9]{32,}$" .env || fail "Missing/weak $key in .env"
done
docker network inspect baize-publishing >/dev/null 2>&1 ||
  docker network create --driver bridge baize-publishing >/dev/null
docker compose --env-file .env -f compose.yaml config --quiet
log 'Loading tested offline Docker image from image.tar.gz'
docker load -i image.tar.gz >/dev/null
docker image inspect baize-wechatsync-mcp:baize-dev >/dev/null ||
  fail 'Expected image tag baize-wechatsync-mcp:baize-dev was not present'
log 'Starting MCP SSE and Chrome WebSocket bridge'
docker compose --env-file .env -f compose.yaml up -d --no-build --pull never
docker compose --env-file .env -f compose.yaml ps
log 'Chrome Extension URL on the Docker host: ws://127.0.0.1:9527'
log 'MCP SSE URL inside baize-publishing network: http://wechatsync-mcp:9528/sse'
log 'Host-local MCP health: http://127.0.0.1:9528/health'
log 'Keep .env secret. Configure Chrome token from WECHATSYNC_TOKEN, Manager token from WECHATSYNC_HTTP_TOKEN.'
